### ISSUE TITLE
:react-native-calendar-events:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by vseprav** [wmcmahan/react-native-calendar-events#70]
After update to version 1.4.0 I got error when run `cd android && ./gradlew assembleRelease`
```
:react-native-calendar-events:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/opt/app/gift_demo/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:29: error: cannot find symbol
import com.facebook.react.bridge.Dynamic;
                                ^
  symbol:   class Dynamic
  location: package com.facebook.react.bridge
/opt/app/gift_demo/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:114: error: cannot find symbol
    public WritableNativeArray findEvents(Dynamic startDate, Dynamic endDate, ReadableArray calendars) {
                                          ^
  symbol:   class Dynamic
  location: class CalendarEvents
/opt/app/gift_demo/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:114: error: cannot find symbol
    public WritableNativeArray findEvents(Dynamic startDate, Dynamic endDate, ReadableArray calendars) {
                                                             ^
  symbol:   class Dynamic
  location: class CalendarEvents
/opt/app/gift_demo/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:685: error: cannot find symbol
    public void findAllEvents(final Dynamic startDate, final Dynamic endDate, final ReadableArray calendars, final Promise promise) {
                                    ^
  symbol:   class Dynamic
  location: class CalendarEvents
/opt/app/gift_demo/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:685: error: cannot find symbol
    public void findAllEvents(final Dynamic startDate, final Dynamic endDate, final ReadableArray calendars, final Promise promise) {
                                                             ^
  symbol:   class Dynamic
  location: class CalendarEvents
5 errors
:react-native-calendar-events:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-calendar-events:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```
## My dependency
"react-native": "0.41.2",
"react-native-calendar-events": "1.4.0"

**Comment by wmcmahan** [comment]
Hey @vseprav, I'm not exactly sure why its not finding the Dynamic class. If you have not already tried, run `./gradlew clean` before `./gradlew assembleRelease`.

**Comment by mariapotashnyk** [comment]
I have the same error
./gradlew clean before ./gradlew assembleRelease does not help

**Comment by vseprav** [comment]
switched to 1.3.6 version and all works

**Comment by wmcmahan** [comment]
@vseprav @mariapotashnyk I think the class Dynamic was introduced in React Native's 0.42.0 release. If possible, you can try updating your version of React Native to gain reference to the new class. I will also make a note in the readme.

**Comment by rodrigooler** [comment]
Here also occurs the error, someone managed to solve?

<img width="726" alt="screen shot 2017-08-22 at 12 19 57" src="https://user-images.githubusercontent.com/5496931/29573159-a5f5c414-8734-11e7-8380-2b51c769c44c.png">

**Comment by wmcmahan** [comment]
@rodrigooler, v1.4.2 of this package needs the latest RN 0.47 release. For prior releases, you can use v1.4.1.

**Comment by DarthFowla** [comment]
I'm actually getting this very same error after upgrading to RN 0.50.0

    "react-native": "0.50.0",
    "react-native-calendar-events": "^1.4.3"

So now what? Why is this a recurring issue in this package?

**Comment by sibelius** [comment]
it is fixed on master, we can close this

**Comment by anagar23** [comment]
I am still getting this error and not able to solve it. I have tried different versions and latest one as well but no luck.
I am on React-Native version - 0.59.0

**Comment by ldco2016** [comment]
@anagar23 , I got the same error as you did two days ago, were you able to solve it? Should a new issue be opened?

```
/Users/danale/Projects/NFIBEngage/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:14: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
/Users/danale/Projects/NFIBEngage/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:15: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
/Users/danale/Projects/NFIBEngage/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:71: error: cannot find symbol
        ActivityCompat.requestPermissions(currentActivity, new String[]{
        ^
  symbol:   variable ActivityCompat
  location: class CalendarEvents
/Users/danale/Projects/NFIBEngage/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:95: error: cannot find symbol
        int writePermission = ContextCompat.checkSelfPermission(reactContext, Manifest.permission.WRITE_CALENDAR);
                              ^
  symbol:   variable ContextCompat
  location: class CalendarEvents
/Users/danale/Projects/NFIBEngage/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:96: error: cannot find symbol
        int readPermission = ContextCompat.checkSelfPermission(reactContext, Manifest.permission.READ_CALENDAR);
                             ^
  symbol:   variable ContextCompat
  location: class CalendarEvents
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-calendar-events:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by matheusbaumgart** [comment]
Also getting this issue on React Native 0.61.1

**Comment by ldco2016** [comment]
@matheusbaumgart , try `npm run jetify`

**Comment by mezhik91** [comment]
I have the same issue with 0.62 :/

**Comment by waqaramjad** [comment]
same error

**Comment by kmanishk1** [comment]
same issue

**Comment by MoOx** [comment]
Please try latest version (2.x) and see if the issue persist.
